### PR TITLE
SummaryPane

### PR DESCRIPTION
**Pull request by jc-healy**
Cleaned up the math on feature importance summarizer.  
Refactored out SummaryPane's into two separate namespaces.
Added appropriate documentation.

### CODE REVIEW

**Review by hamelin — CHANGES_REQUESTED** [review]
1. In `doc/plotsummarypane_feature_importance.ipynb`, I suggest we take out the lines commented out from the next-to-last cell.
2. The functionality has been split from a single `tnt.summary` submodule to a pair of submodules `tnt.summarizer_dataframe.py` and `tnt.summarizer_plot`. This seems awkward to me. Why not instead have `summary` become a package (which we could rename to `summarizer` or `summarizers`, I have no problem with that) with submodules `dataframe.py` and `plot.py` instead? You would still get `tnt.summary.dataframe` and `tnt.summary.plot` as importables. Plus, you then get the opportunity to put code that is useful for both types of summarizers under that `tnt.summary.__init__.py` submodule. I feel that if there is a good time to make that change, it would be now, before this progress becomes a de facto API. @lmcinnes , do you have an opinion on this naming nit I'm picking?

**Comment by jc-healy** [comment]
Sounds like a plan, Ben.  I'll try and make those changes today.

**Comment by hamelin** [comment]
> Sounds like a plan, Ben. I'll try and make those changes today.

and I'll arrange to revise it in real time. 😬

**Review by hamelin — APPROVED** [review]
Very nice! LGTM

**Pull request merged**
